### ISSUE TITLE
Add generator command for building whole site at once

### ISSUE THREAD

**Issue by Majkl578** [nette/docs#44]
- [x] as HTML
- [x] as PDF
- [ ] as epub/mobi

**Comment by f3l1x** [comment]
Is it still relevant or we can close it?

**Comment by JanTvrdik** [comment]
@f3l1x Please don't spam random issues with pointless questions. Comment only if your comment adds value, otherwise you're just creating noise and wasting valuable type of [many people](https://github.com/nette/docs/watchers).

Example of valuable comment „I this should be closed, because <your reasons>“. Or (less useful, but better that your comment) „I think that this is important, because <your reasons>“.

**Comment by f3l1x** [comment]
@JanTvrdik Oh sorry, I didn't want to be mean. This issue is so old and I don't get a point or have the whole context. My intention was to make some activity and resolve (discuss, close or what..) old issues. 

I try to better: I think this should be closed, because it's not relevant for me anymore.
